In [1]:
import pandas as pd
df = pd.read_csv('clean_tweets.csv')

In [2]:
df.head(1)

,name,retweet_count,text,created_at,favourite_count,hashtags,sentiment_a,stopwords,clean_words,polarity,sentiment
0,Pomp,0,wild,2021-03-08,61,[],['wild'],"['i', 'me', 'my', 'myself', 'we', 'our', 'ours...",[' wild '],0.1,positive

In [3]:
new_df = df.drop(labels=['name','text','sentiment_a','stopwords','favourite_count','polarity','hashtags'],axis=1)

In [4]:
new_df

,retweet_count,created_at,clean_words,sentiment
0,0,2021-03-08,[' wild '],positive
1,125,2021-03-08,['if you had invested your 1200 stimulus check...,neutral
2,3,2021-03-08,[' how is your paper trading account going'],neutral
3,132,2021-03-08,['update gamestop closed today at 194 per shar...,positive
4,6,2021-03-08,['daily letter this morning is pretty spot on ...,positive
...,...,...,...,...
24336,21,2017-05-29,['update etc trading volume within 24hour '],neutral
24337,0,2017-05-29,[' no matter how good of a trader you are 100 ...,positive
24338,76,2017-05-29,['etc is hot now preparing for upmove long tim...,positive
24339,0,2017-05-29,[' if everybody gets dumped on why does everyo...,neutral
24340,0,2017-05-29,[' dreams great messengers they are'],positive

In [5]:
new_df['clean_words']=[i[2:-2] for i in new_df['clean_words']]

In [6]:
new_df

,retweet_count,created_at,clean_words,sentiment
0,0,2021-03-08,wild,positive
1,125,2021-03-08,if you had invested your 1200 stimulus check i...,neutral
2,3,2021-03-08,how is your paper trading account going,neutral
3,132,2021-03-08,update gamestop closed today at 194 per share ...,positive
4,6,2021-03-08,daily letter this morning is pretty spot on wi...,positive
...,...,...,...,...
24336,21,2017-05-29,update etc trading volume within 24hour,neutral
24337,0,2017-05-29,no matter how good of a trader you are 100 wi...,positive
24338,76,2017-05-29,etc is hot now preparing for upmove long time ...,positive
24339,0,2017-05-29,if everybody gets dumped on why does everyone...,neutral
24340,0,2017-05-29,dreams great messengers they are,positive

In [7]:
new_df.to_csv('wordcloud.csv', index=False)